filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /tmp/importer/nebula-importer-*.log

filebeat.storage.provider: azureBlob
filebeat.storage.upload_dir: /tmp/uploader
filebeat.storage.container: ng5f0013

output.file:
  path: /tmp/uploader
  filename: importer.log
  rotate_every_kb: 0
  rotate_every_line: 20
  number_of_files: 10
  permissions: 0600

processors:
  - drop_fields:
      fields: ["host", "ecs", "agent", "input", "log"]
