filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /tmp/nebula-importer-*.log

filebeat.storage.provider: azureBlob
filebeat.storage.upload_dir: /tmp/uploader

output.file:
  path: /tmp/uploader
  filename: importer.log
  rotate_every_kb: 0
  rotate_every_line: 10000
  number_of_files: 1024
  permissions: 0600
